### ISSUE TITLE
Enable RegistryInputDialog to work standalone and use with iBioSim

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#148]
Should be used with both SBOLAssociation and as a new Import -> SynBioHub menu item.

**Comment by michael13162** [comment]
I've added this to SBOLAssociationPanel2.  It currently only works with the "Working Document" (I think).  I've updated SBOLDesigner's RegistryInputDialog to work better standalone, but am having a hard time updating iBioSim's reference of SBOLDesigner due to not being able to build SBOLDesigner into a jar.  

I remember you were having problems with this as well a while ago.  Did you figure out what was going wrong?

**Comment by cjmyers** [comment]
Hmm, I really need to write these things down.  I will take a look on my flight and see if I can get it to work.

**Comment by michael13162** [comment]
I've updated SBOLDesigner to include a new interface for RegistryInputDialog.  iBioSim now uses this new interface to select parts from the working document (which is now passed in) as well as any other registry.  Everything seems to be working correctly as of now.  Closing issue.

**Comment by cjmyers** [comment]
Should use recursive copy instead, so sub-structure comes in.

**Comment by michael13162** [comment]
This wasn't actually a bug, and there was different bug with not adding just the root, but I've fixed this.  Closing again.
