### ISSUE TITLE
Update Message Dialog

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOLDesigner#156]
The message does not reflect button text.

<img width="651" alt="screen shot 2017-04-26 at 5 02 57 pm" src="https://cloud.githubusercontent.com/assets/7537729/25460738/573a559a-2aa2-11e7-945f-fa96904801a0.png">

**Comment by michael13162** [comment]
This actually isn't a bug.  The text is "Please edit it and/or its parents and choose "yes" to creating an editable copy while re-saving".  It is asking you to click "OK", then edit that part's parents and/or itself, and then saving an edited copy and choosing "yes" to bringing it into your namespace.

**Comment by tramyn** [comment]
Then where do you click yes?

**Comment by michael13162** [comment]
![image](https://cloud.githubusercontent.com/assets/14242505/25499973/87e3d3bc-2b4a-11e7-9864-b7ec10b0471e.png)

After opening it and/or its parent parts, if you try to click save after editing, the prompt above will be shown.  It's asking if you want to copy the part into your own namespace, since we only allow you to make changes to parts in your own namespace.  

If you're currently in MEB, I'm planning on coming down in 30 min or so and can show you in person.
