### ISSUE TITLE
Working document in search should load the file

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#182]
This document should be the one on disk, not the document in memory.

**Comment by michael13162** [comment]
I figured out what was going on here.  Originally, RegistryInputDialog did indeed look for the working document on disk.  However, because iBioSim wanting to search from a SBOLDocument in memory, I added a new constructor that took in a SBOLDocument.  I then switched all my calls to RegistryInputDialog to this new constructor.  This commit merely switches it back and leaves the new constructor for iBioSim's uses.
