### ISSUE TITLE
Change Options button on select part from registry page to Login

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#183]
This button should allow the user to login to the selected registry.

**Comment by michael13162** [comment]
This button brings up the Registry preferences page, which allows the user to log in.

I could add a separate login button, but this doesn't really seem necessary.  Also, logging in is only applicable to SynBioHub instances, so it doesn't make sense to always have it there.

Could you explain why you want this change?

**Comment by cjmyers** [comment]
This is part of the larger issue of having separate SBOLDesigner and iBioSim preferences when used as a plugin.  We could perhaps leave the Options button but it would need to bring up the iBioSim preferences when used in that context.  Please discuss with @tramyn.

**Comment by michael13162** [comment]
Ah, I see.  I can make a static Functor in RegistryInputDialog that SBOLDesignerPlugin can set to be iBioSim's preferences dialog.  The options button can call this Functor, and the default implementation can be SBOLDesigner's preferences.  This is definitely hacky, but will allow us to not have SBOLDesigner depend on iBioSim.  @tramyn , what do you think?

**Comment by cjmyers** [comment]
We need to ensure also that it is this preference you are using when in plugin as I noticed students having problems with setting preferences in iBioSim but your preferences getting used and throwing errors when not setup properly.

**Comment by michael13162** [comment]
Unfortunately, I don't think there is a clean way to do this.  SBOLDesigner should definitely not depend on iBioSim.  The workaround would have to be passing in a function pointer that overrides behavior.  However, I'm not even sure this is possible in Java since SBOLDesigner will have to call a different preferences dialog dynamically.

**Comment by cjmyers** [comment]
Maybe what we need to do is have iBioSim's preference dialog use and update SBOLDesigner's preferences.  This does mean whether you use in SBOLDesigner or iBioSim, you would have the same preferences, but this seems like it might actually be better.  Could you fix this in iBioSim?  The code is basically the same.  It is in iBioSim-gui, in util/PartEditorPreferencesTab.java

**Comment by michael13162** [comment]
I followed the installation steps on iBioSim's README.  However, I'm getting:
Missing artifact uk.ac.ncl.intbio:vpr-rdf-util:jar:2.0.2-SNAPSHOT
Missing artifact uk.ac.ncl.intbio:vpr-rdf-util:jar:2.0.2-SNAPSHOT
Missing artifact uk.ac.ncl.ico2s:vpr-data:jar:2.0.2-SNAPSHOT

Running the maven steps also messed up my SBOLDesigner build.  Specifically, generate sources doesn't seem to be actually resolving the dependencies.  I've removed BOOSTDialog from the classpath since that's the culprit, and it isn't even being used.

**Comment by cjmyers** [comment]
These are tramy’s libraries. Please put issue on ibiosim tracker. Try mvn clean and mvn install if you haven’t already. Otherwise see tramy.

Chris

**Comment by tramyn** [comment]
@michael13162 : If you are trying to access iBioSim from the frontend, make sure you:
1. check out the latest updates from SBOLDesigner and libSBOLj. Perform mvn install on each project directory.
2. navigate to iBioSim's gui module and perform mvn clean then mvn install.

If these steps fail to build, let me know and we can debug this together.

As for the other discussion mentioned in this issue, I would prefer it if iBioSim has its own preferences and likewise for SBOLDesigner. Any information that iBioSim needs from SBOLDesigner in regards to registries should be obtained from the backend of SBOLDesigner. Is there a reason as to why we should be modifying SBOLDesigner's UI?

**Comment by michael13162** [comment]
I also agree with @tramyn that it would make more sense for the Registry preferences to just live in one place (in SBOLDesigner).  Duplicating all the code in iBioSim is more messy, and keep track of changes/plumbing to get everything to work together properly is difficult.

iBioSim could just access the same preferences node when it needs the information.  This is definitely cleaner.

**Comment by cjmyers** [comment]
I agree, but I struggled with this.  I was not able to disentangle the dependencies.  Namely, it would be good to have the PartEditorPreferencesTab be housed in SBOLDesigner, but it implements PreferenceTab, so I assume this must also be in SBOLDesigner.  However, for some reason I ended up needing to duplicate it in iBioSim.  If you two can figure out how to just have the SBOLDesigner preferences tab show up in the iBioSim's preferences that would be great.

**Comment by michael13162** [comment]
The Options button has been replaced by Login button.  The Login button is also sensitive to whether a loginable registry is selected.  I was having strange issues have both login and options, so now it's just login.  The old implementation for options has been commented out.  Login also refreshes the table since new parts are now potentially available.
