### ISSUE TITLE
Add a version field to the edit component window

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#19]
When this field is changed, behavior should be similar to when displayId is changed. Namely, if CD with generated URI exists, give error, else create a copy with new identity.

**Comment by michael13162** [comment]
I think there might be something I'm not understanding when it comes to versions.

For example:
1. create a CD with URI "http://mz/Pro"
2. create a CD with URI "http://mz/Pro/1" (same CD as before, but with version set to 1)
3. delete "http://mz/Pro" from the document
4. then shouldn't I be able to create a CD with URI "http://mz/Pro" since it is no longer in the document anymore?

**Comment by cjmyers** [comment]
You should never have an object with a version and the same object without a version.  The problem is that the persistent identity for an object with a version would match this object.  So, either:

1) There is only one version of an object with identity/persistentIdentity of http://mx/Pro
2) There are multiple versions of an object with identity http://mx/Pro/1, http://mx/Prob/2, etc. with all sharing the same persistentIdentity http://mx/Pro.

**Comment by michael13162** [comment]
In that case, this issue can be closed.
