### ISSUE TITLE
Add an All Collections option to Collection pull down

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#215]
Using SBOLDesigner-2.2 on m Mac, when I try to import standard parts like J23101 from SynBioHub, nothing is found.

**Comment by cjmyers** [comment]
![screen shot 2018-01-16 at 2 22 06 pm](https://user-images.githubusercontent.com/3507191/35012912-ba150754-fac8-11e7-8e5b-a19707935359.png)

**Comment by cjmyers** [comment]
Shows up for me.  Did you select synbiohub.org?  Did you click on the igem collection?  Can you let us know which collection you were in when you could not find this part?

**Comment by jakebeal** [comment]
I selected SynBioHub.org, and then searched in "All Collections"
When I click on the "Collection" menu, that is the only option there is.

I see that when I double-click on igem_collection it then puts it in the menu and I can find it, but that's completely non-intuitive to me as an interface. Why can't I find it searching all collections? Why can't I get a collection through the collections menu?

**Comment by cjmyers** [comment]
Ah I see now.  The Collections menu is designed like the file tree on Mac.  If you click on say “attach” in Mail.  It brings up a file browser where the top is your current location in the file hierarchy, you can use this browse up the file hierarchy but not down.  

What you are asking for is equivalent to a recursive dive through all collections and giving you access to all parts even from the root.  This will be VERY slow.  Think of it like a recursive “ls” over your entire hard disk.  Even filtering by collection and part type, can be slow sometimes such as for CDS.  I’ve logged an issue about this to see if we cannot optimize the queries some as it is firing queries on each thing you type in the search box.  

To address this, I suggest changing “All Collections” to “Root Collections”.  Then, we should also consider another way to search recursively over all parts, but this should be used with caution as it can be slow, since SPARQL queries on string can be slow sometimes.

**Comment by jakebeal** [comment]
If it's meant to act like a file tree, then it needs to look and act like a file tree.  Right now, it's set up to look and act like a search bar, which is an entirely different user experience.

I think being a file tree would be a bad idea, since there is very little hierarchy in the organization of parts collections. Being a search bar makes a lot more sense.

Furthermore, I don't believe that searching all collections needs to be slow: the "spotlight" function on my Mac happily searches the entirety of my disk at lightning speed.

**Comment by michael13162** [comment]
Your Mac is fast because it uses an index to store the strings to allow for fast retrieval.  Our Sparql queries are slow because the data isn't stored in a index, and has to travel over the network.  I agree this needs to be improved, but it isn't a simple task.  The best approach might be that of a cache, which our implementation already kind of does, but it still doesn't avoid the initial retrieval.  Another option would be setting up something like elastic search, but that's a project in it's own right.

**Comment by cjmyers** [comment]
Totally agree that search needs to be optimized and faster.  Also, I totally agree that a means to search that ignores collection organization is also important.  However, I would not be keen to put all Collections in the collections selection bar though as I think this could be too many.  While collections may not be currently perfectly organized hierarchically, I think it would be great to try to work at organizing things in this way.  It would should make finding things easier I think. 

However, we could include both "All Collections" and "Root Collections" in this box, and when All Collections is selected, it will literally include all objects independent of which Collection(s) they reside in.  Right now this will likely be slow, but we will think about how to optimize this.

**Comment by jakebeal** [comment]
If you can query the iGEM parts collection, you can probably query anything reasonable that's being stored right now.

**Comment by cjmyers** [comment]
We can but it is a bit slow for queries that return more than a couple thousand results.  Furthermore, when the number of results is over 10000, we need to do multiple queries to get all the results, since each query is restricted to 10k max return.  Right now, we are re-sending queries each time you type in the query box, and this can generate a lot of queries in flight at a time.  We need to figure out a way to handle this better to ensure we are not sending redundant queries or ones we are going to end up ignoring the results of.  Michael: let's discuss this.

**Comment by cjmyers** [comment]
To address this issue at least in part, please add an All Collections option that does a search query without any Collection being provided.
