### ISSUE TITLE
Saving into existing SBOL file

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#24]

**Comment by cjmyers** [comment]
When saving, should first check if the file exists.  If it does, the file should be read into a new document.  If the root CD already exists in the document, the user should be given the option to: 
1) Overwrite - in this case, it should remove the root CD and all other objects that exist in the document before adding in the root CD and its children.
2) New version - in this case, it should copy the root CD and all its children with the version incremented.
3) Cancel - do not save

**Comment by michael13162** [comment]
Done.  This feature really gives the "open multiple rootCDs" feature a lot of utility.  Now, a single SBOL file can contain entire workspaces of designs, all with different versions.  

To test, create a new random design, and save it as a new version of an existing SBOL file.  Then, open the file, and now you can select either the original contents of the file or the new version of the design you just saved.

**Comment by michael13162** [comment]
Bug with writing a new version.  We have to update all references to new version as well.

**Comment by cjmyers** [comment]
Not necessarily.  Let’s assume we have a CD cd1 that refers to CD cd2 as a Component.  There are two ways this references can be made, either by its identity (i.e., cd2/1) or its persistentIdentity (cd2).  If it is the former, you should not necessarily update the reference, since it is referencing a particular version of cd2.  However, if it is the later, there is no need to update the reference, since the reference is by definition to the latest version.

This does mean that when you are adding a reference to a CD, you will need a means to indicate whether you want to reference a specific version OR the latest version.  If the identity==persistentIdentity (i.e., there is no version), then you do not need to ask, but if there is a version, then we need to ask which type of reference to make.

**Comment by michael13162** [comment]
In the case of writing a new version to an existing file, don't we always want to update the references to point to the new version?  For example, I'm currently just updating all the TopLevels in the new design/version, but when saving on top of the existing file, a validation error saying "sbol-10202: The identity property of an Identified object MUST be globally unique. : http://mz/Pro" gets thrown.  This is because the saved document will contain http://mz/Pro and http://mz/Pro/1.

**Comment by cjmyers** [comment]
This is going to be a little tricky.  As I mentioned earlier, an identity without a version is same as persistentIdentity of something with a version.  This means if you create an object without a version, then change your mind and give it a version then you must remove the one without the version.  In this case, you would potentially need to update the references.  However, I suppose it might still be okay, since they would be using persistent identity.

For example, CD cd1 refers to CD cd2 as a component.  You then introduce a cd2/1.  You would then need to remove cd2 or perhaps change it to cd2/0.  Now, cd1 refers to cd2 which is persistentIdentity for both cd2/0 and cd2/1, and it would return cd2/1 as the latest version.

Chris

**Comment by zgzn** [comment]
This is interesting. I just created a simple example describing the scenario. You need to rename the attached file to .java in order to execute. Here is what I found.
(1) If your SBOLDocument is complete, you will need to first remove the component which is the child of cd1 and has its "definition" field referencing cd2. This is the "comp2" in the attached file. You may then remove cd2. If comp2 is not removed first, you will get an SBOL validation exception 10604, because your component comp2 does not refer to a component definition in this document. This happens only if your document is complete. 
(2) When I created component "comp2_v2", I only provided the display ID of cd2_v2 (line 21). This method assumes an empty version. So when I retrieve the definition URI for this component (line 26), it returns the persistent identity URI of cd2_v2, not its identity URI which has a "2.0" as its version in the end. If you want to get its identity URI, you can get cd2_v2 first and then get its identity, like line 27. So make sure you call the right method to retrieve persistent identity and/or identity. The other way to avoid this is to provide the correct version when creating the component (line 22). 
[persistentIdTest.txt](https://github.com/SynBioDex/SBOLDesigner/files/310095/persistentIdTest.txt)

**Comment by michael13162** [comment]
Duplicate issue
