### ISSUE TITLE
Selecting parts from registry not working

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#240]
When I select a built-in part.  It does not seem to assign it to the part.

**Comment by cjmyers** [comment]
Actually seems I cannot select parts from any registry now.

**Comment by michael13162** [comment]
This was a bug that was caused by a "fix" of another bug dealing with renaming and updating the canvas (since we're now renaming instead of createCopy <- there were slight differences).  Chris reverted the renaming fix and I think I've now fixed the renaming bug in a different way that doesn't break anything else.

**Comment by cjmyers** [comment]
Looks good closing.
