### ISSUE TITLE
CDs downloaded from SynBioHub load as blanks

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#259]
The iGEM16 parts collection was created in SBOLDesigner: 
https://synbiohub.org/public/iGEM_2016_interlab/iGEM_2016_interlab_collection/1

When I download this collection and inspect the XML, everything looks correct. When I load it into SBOLDesigner, it finds all of the five ComponentDefinitions, as expected, but when I actually select one and load it, I get a blank canvas.

(Using SBOLDesigner 3.0, Java 8)

**Comment by cjmyers** [comment]
This is actually a SynBioHub issue.  When you download the SBOL for a Collection, it does not recursively pull all dependencies, it only downloads those items that are members of the collection.    This was done to speedup SBOL download for Collection, which is very very slow, if you make it do a recursive dive to fetch all dependencies.  If you had instead downloaded a single part, then opened it in SBOLDesigner, it should view fine, I just tested this.

Ok, actually, there is another way around this.  We can make SBOLDesigner pull any missing parts into its document from registries that it is aware of.

**Comment by jakebeal** [comment]
I think that the SBOLDesigner modification that you propose is a good and appropriate one, as it fits with the "no duplication" policy enforced by SynBioHub.  

Otherwise, you have a "no round trip" workflow of: "build collection in SBOLDesigner, upload to SynBioHub, download from SynBioHub, can't open collection in SBOLDesigner any more"

**Comment by cjmyers** [comment]
I just added a feature to have it fetch missing parts from web-of-registries, when it cannot find them in the local document.  This opened up your designs.  I've checked in this change though I've asked @michael13162 to modify the code to use the local registry list rather than web-of-registries, so we would pickup SBH's that the user have added via preferences.

**Comment by michael13162** [comment]
I've modified the code to populate the document's registries from both local preferences and the web of registries.  It's also been extracted to SBOLUtils.populateRegistries(doc).

**Comment by michael13162** [comment]
I've looked through your commit and I do believe this is the correct way of implementing this.  If any part comes in through registry or some other dialog, then the missing parts would still be fetched since the document already has populated registries at that point.  I have removed the println though.
