### ISSUE TITLE
Add ability to manage working document better

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#90]
When I tried to attach part descriptions in an unsaved file, it defaulted to working file parts and gave me errors saying it couldn't read the file.

**Comment by michael13162** [comment]
Before, the working document represented the file that was previously opened or saved.  There's a reason I did this, but I honestly don't remember anymore.  Either way, it now represents the design that is currently open, so if you're editing a design/root CD in a bigger SBOLDocument, then you'll only have access to that particular design in the working document instead of all parts in the entire SBOLDocument.

This does make more sense, so I'll close the issue for now.  If you want access to parts in the greater SBOLDocument, then you could always use the import part button in the part editor and navigate to the correct file.

**Comment by michael13162** [comment]
This isn't the best way to fix this.  Reopening issue.

**Comment by cjmyers** [comment]
Open means open a working document.
New should mean create a new working document.
New Part to create a new part within the existing working document.
New Document
New Part
Open Document
Open Part

**Comment by cjmyers** [comment]
New Document / Open Document are new icons likely look for folder icons.
New Part / Open Part also need to have icons.

New Document - change the working document and start a new part in the canvas

Open Document - change the working document and allows you to choose a part with an "Open" button OR create a new part with a "New" button

New Part - creates a new part in the canvas, when saved goes into the current working document by default.

Open Part - allows you to select a part to open from the existing working document, same browser just don't need to select file first.

Save always saves to the working document.

When you open SBOLDesigner, it creates a default working document.  When working with the default working document, save has an extra step to ask you where to save.  Note while in this state, you should not have Working Document as a registry option.

**Comment by michael13162** [comment]
Closing this issue and opening a new issue on revamping all icons.
